name: Publish CI

on:
	pull_request:
		branches:
			- master
		types: [closed]

env:
  NODE_VERSION_USED_FOR_DEVELOPMENT: 16

jobs:
	tests:
		runs-on: ubuntu-latest
		steps:
			- name: Checkout repository
				uses: actions/checkout@v2

			- name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION_USED_FOR_DEVELOPMENT }}
					cache: 'npm'

      - name: Install Dependencies
        run: npm ci

			- name: Lint ESLint
        run: npm run test:eslint

			- name: Run Jest Tests
        run: npm run test:jest

	publish:
		if: github.event.pull_request.merged == true
		runs-on: ubuntu-latest
		needs: [tests]
		steps:
			- name: Checkout repository
				uses: actions/checkout@v2

			- name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION_USED_FOR_DEVELOPMENT }}
					cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build NPM package
        run: npm run build

			- name: Deploy to `npm`
        run: npm run gitpublish:npm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
